name: flexpace
description: 플렉스페이스
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.2.0
  get: ^4.6.6
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  flutter_screenutil: ^5.9.0
  flutter_local_notifications: ^17.1.0
  permission_handler: ^11.0.1
  url_launcher: ^6.2.4  # 최신 버전으로 업데이트
  flutter_svg: ^2.0.7
  flutter_secure_storage: ^9.0.0  # 최신 버전으로 업데이트
  intl: ^0.19.0
  image_picker: ^1.0.4
  cloud_firestore: ^5.4.4
  package_info_plus: ^8.0.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  logger: ^2.4.0
  kakao_flutter_sdk: ^1.9.5
  sign_in_with_apple: ^6.1.3
  flutter_naver_login: ^2.1.0
  google_sign_in: ^6.2.1
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0
  cloud_functions: ^5.1.3
  flutter_naver_map: ^1.3.0+1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  icons_launcher: ^3.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/splash/
    - assets/icon/
    - assets/social/
    - assets/main/
    - assets/sidebar/
  fonts:
    - family: SUIT
      fonts:
        - asset: assets/font/SUIT-Variable.ttf


icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/icon.png"
      adaptive_background_color: '#782DFA'
      # adaptive_background_image: "assets/icon.png"
      adaptive_foreground_image: "assets/icon.png"
      adaptive_round_image: "assets/icon.png"
      adaptive_monochrome_image: "assets/icon.png"
    ios:
      enable: true

